defaults:
  - experiment/hyperparameters: default
  - experiment/model: sequence-srn-inattentive
  - experiment/dataset: alice-2

  - hydra/output: custom

experiment:
  name: test

pretty_print: False
