defaults:
  - experiment/hyperparameters: default
  - experiment/model: sequence-srn-inattentive
  - experiment/dataset: alice-herself

  - hydra/output: custom

experiment:
  name: experiment-1

pretty_print: False
