defaults:
  - experiment/hyperparameters: default
  - experiment/model: default
  - experiment/dataset: alice-herself

  - hydra/output: custom

# experiment:
#   name: alice-herself

pretty_print: True
